sdf_map/box_min_x: -13.9
sdf_map/box_min_y: -7.3
sdf_map/box_min_z: 0.7

sdf_map/box_max_x: 15.9
sdf_map/box_max_y: 27.4
sdf_map/box_max_z: 2.0

sdf_map/map_size_x: 35.0
sdf_map/map_size_y: 55.0
sdf_map/map_size_z: 4.0

sdf_map/resolution: 0.10
